# Generated by Django 3.1.13 on 2022-08-01 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_No', models.CharField(max_length=100)),
                ('owner_name', models.CharField(max_length=100)),
                ('manufacture_company', models.CharField(max_length=200)),
                ('insurance_valid_till', models.DateField()),
                ('permit_tax_valid_till', models.DateField()),
                ('fitness_valid_till', models.DateField()),
            ],
        ),
    ]
