# Generated by Django 3.1.13 on 2022-08-01 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_management', '0002_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='manufacture_company',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='owner_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='registration_No',
            field=models.CharField(max_length=50),
        ),
    ]
