# Generated by Django 3.1.13 on 2022-08-01 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport_management', '0003_auto_20220731_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='registration_No',
            new_name='registration_no',
        ),
    ]
