# Generated by Django 3.1.13 on 2022-08-01 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport_management', '0004_auto_20220731_1806'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMaintanance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_initialization', models.DateField()),
                ('odometer_reading', models.IntegerField()),
                ('oil_changed', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('spare_parts_replaced', models.CharField(max_length=300)),
                ('total_cost_of_maintenance', models.IntegerField()),
                ('vehicle_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_management.vehicle')),
            ],
        ),
    ]
