# Generated by Django 3.1.13 on 2022-08-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_management', '0005_vehiclemaintanance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.IntegerField(default=91)),
                ('liscence_no', models.CharField(max_length=50)),
                ('liscence_expiry_date', models.DateField()),
                ('aadhar_card_no', models.IntegerField(unique=True)),
                ('joining_date', models.DateField()),
                ('remarks', models.CharField(max_length=220)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
