# Generated by Django 3.1.13 on 2022-08-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_management', '0006_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemaintanance',
            name='under_maintanance',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=10),
        ),
    ]
