# Generated by Django 3.1.13 on 2022-08-01 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport_management', '0008_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_product', models.IntegerField()),
                ('weight_in_tons', models.IntegerField()),
                ('location_from', models.CharField(default='', max_length=100)),
                ('location_to', models.CharField(default='', max_length=100)),
                ('loading_date', models.DateField()),
                ('freight_amount', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('decline', 'Decline'), ('approved', 'Approved'), ('processing', 'Processing'), ('complete', 'Complete'), ('deliverd', 'Delivered')], default='pending', max_length=10)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_management.client')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_management.driver')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_management.product')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport_management.vehicle')),
            ],
        ),
    ]
